#!/usr/bin/python
# -*- coding: cp1252 -*-
#
# Sudoku Generator and Solver in 250 lines of python
# Copyright (c) 2006 David Bau.  All rights reserved.
#
# Can be used as either a command-line tool or as a cgi script.
#
# As a cgi-script, generates puzzles and estimates their level of
# difficulty.  Uses files sudoku-template.pdf/.ps/.txt/.html
# in which it can fill in 81 underscores with digits for a puzzle.
# The suffix of the request URL determines which template is used.
#
# On a command line without any arguments, prints text for a
# random sudoku puzzle, with an estimate of its difficulty.
# On a command line with a filename, solves the given puzzles
# (files should look like the text generated by the generator).
#
# Adapted for Adafruit_Thermal library by Phil Burgess for Adafruit
# Industries.  This version uses bitmaps (in the 'gfx' subdirectory)
# to render the puzzle rather than text symbols.  See sudoku-txt
# for a different Sudoku example that's all text-based.

from Adafruit_Thermal import *
import SteriLogo as logo
from subprocess import call


printer = Adafruit_Thermal("/dev/ttyS1", 19200, timeout=5)


# Test inverse on & off
printer.inverseOn()

printer.inverseOff()

call(["echo"," 1 >> /dev/ttyS1"])


def main():
    # Test more styles
    printer.justify('L')
    printer.boldOn()
    printer.println("--------------------------------")
    printer.println("Fecha: 2016-06-28        ")
    printer.println("Inicio: 14:35:24         ")
    printer.println("Fin:     07:23 pm          ")
    printer.println("Ciclo:     777           ")
    printer.println("Tipo:     134 °C            ")
    printer.println("--------------------------------")
    printer.println("Parametros Ciclo         ")
    printer.println("Est:     4 min            ")
    printer.println("Sec:    10 min            ")
    printer.println("--------------------------------")
    printer.println("Preparación:   ")
    printer.println("14:35:24    89.99   C  12.75 psi")
    printer.println("14:36:24    84.14    C  12.74 psi")
    printer.println("14:37:24    83.60    C  12.74 psi")
    printer.println("Pre Vacio:   ")       
    printer.println("14:38:24  83.07    C  13.02 psi")
    printer.println("14:39:24  97.10    C  35.09 psi")
    printer.println("14:40:24  103.24    C  36.74 psi")
    printer.println("Alcanzando temperatura:   ")
    printer.println("14:41:24  105.57    C  37.04 psi")
    printer.println("14:42:24  132.37    C  42.55 psi")
    printer.println("14:43:24  133.92    C  44.06 psi")
    printer.println("Esterilizando:   ")   
    printer.println("14:44:24  134.20    C  44.02 psi")
    printer.println("14:45:24  134.16    C  43.97 psi")
    printer.println("14:46:24  133.93    C  43.97 psi")
    printer.println("14:47:24  134.16    C  43.98 psi")
    printer.println("Descarga y Secado:   ")
    printer.println("14:48:24  134.18    C  45.66 psi")
    printer.println("14:49:24  121.10    C  23.44 psi")
    printer.println("14:50:24  111.93    C  17.32 psi")
    printer.println("14:51:24  112.91    C  14.85 psi")
    printer.println("14:52:24  114.18    C  13.67 psi")
    printer.println("14:53:24  113.75    C  13.45 psi")
    printer.println("14:54:24  112.50    C  13.23 psi")
    printer.println("14:55:24  104.28    C  4.43  psi")
    printer.println("14:56:24  108.29    C  1.76  psi")
    printer.println("14:57:24  103.20    C  7.00  psi")
    printer.println("14:58:24  95.96    C  10.87 psi")
    printer.println("Normalizando Ciclo:   ")
    printer.println("14:59:24  94.65    C  11.19 psi")
    printer.println("15:00:24  92.26    C  11.41 psi")
    printer.println("15:01:24  103.66    C  12.80 psi")
    printer.println("--------------------------------")
    printer.println("Tiempo inicio Ciclo:     ")
    printer.println("    14:35:24              ")
    printer.println("Tiempo Comienzo Esteri:  ")
    printer.println("    14:44:24")
    printer.println("Tiempo Final Secado:     ")
    printer.println("    14:58:24             ")
    printer.println("--------------------------------")
    printer.println("Temp Promedio: 134.11 ° C   ")
    printer.println("Presion Promedio: 43.98 psi ")
    printer.println("--------------------------------")
    printer.println("Ciclo:    | Aprobado |      ")
    printer.println("--------------------------------")
    printer.boldOff()
    printer.feed(2)

if __name__ == '__main__':
  main()

