// Copyright (C) 1991-2015 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus II License Agreement,
// the Altera MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Altera and sold by Altera or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus II 64-Bit Version 15.0 (Build Build 145 04/22/2015)
// Created on Thu Aug 25 09:05:35 2016

ADC_System ADC_System_inst
(
	.clk_50Mhz(clk_50Mhz_sig) ,	// input  clk_50Mhz_sig
	.selected_channel(selected_channel_sig) ,	// input [2:0] selected_channel_sig
	.ADC_data(ADC_data_sig) ,	// output [11:0] ADC_data_sig
	.ADC_CONVST(ADC_CONVST_sig) ,	// output  ADC_CONVST_sig
	.ADC_SCK(ADC_SCK_sig) ,	// output  ADC_SCK_sig
	.ADC_SDI(ADC_SDI_sig) ,	// output  ADC_SDI_sig
	.ADC_SDO(ADC_SDO_sig) 	// input  ADC_SDO_sig
);

