// Copyright (C) 1991-2015 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus II License Agreement,
// the Altera MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Altera and sold by Altera or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus II 64-Bit Version 15.0 (Build Build 145 04/22/2015)
// Created on Fri Jul 08 10:15:43 2016

max6675_decoder max6675_decoder_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.miso(miso_sig) ,	// input  miso_sig
	.start(start_sig) ,	// input  start_sig
	.finish(finish_sig) ,	// output  finish_sig
	.idle(idle_sig) ,	// output  idle_sig
	.cs(cs_sig) ,	// output  cs_sig
	.sclk(sclk_sig) ,	// output  sclk_sig
	.temp_max6675(temp_max6675_sig) 	// output [15:0] temp_max6675_sig
);

