// Copyright (C) 1991-2015 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus II License Agreement,
// the Altera MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Altera and sold by Altera or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus II 64-Bit Version 15.0 (Build Build 145 04/22/2015)
// Created on Wed May 11 21:20:16 2016

interchanger interchanger_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.ARM_DATA_FROM(ARM_DATA_FROM_sig) ,	// input [31:0] ARM_DATA_FROM_sig
	.ARM_DATA_TO(ARM_DATA_TO_sig) ,	// output [31:0] ARM_DATA_TO_sig
	.ARM_SEL(ARM_SEL_sig) ,	// input [3:0] ARM_SEL_sig
	.ARM_WR(ARM_WR_sig) ,	// input  ARM_WR_sig
	.NIOS_DATA_FROM(NIOS_DATA_FROM_sig) ,	// input [31:0] NIOS_DATA_FROM_sig
	.NIOS_DATA_TO(NIOS_DATA_TO_sig) ,	// output [31:0] NIOS_DATA_TO_sig
	.NIOS_SEL(NIOS_SEL_sig) ,	// input [3:0] NIOS_SEL_sig
	.NIOS_WR(NIOS_WR_sig) 	// input  NIOS_WR_sig
);

