// Copyright (C) 1991-2015 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus II License Agreement,
// the Altera MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Altera and sold by Altera or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus II 64-Bit Version 15.0 (Build Build 145 04/22/2015)
// Created on Sun Aug 21 22:52:41 2016

i2c_slave i2c_slave_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.start(start_sig) ,	// input  start_sig
	.mode_w_r(mode_w_r_sig) ,	// input  mode_w_r_sig
	.data2_write(data2_write_sig) ,	// input [7:0] data2_write_sig
	.read_data(read_data_sig) ,	// output [7:0] read_data_sig
	.receive_ack(receive_ack_sig) ,	// output  receive_ack_sig
	.idle(idle_sig) ,	// output  idle_sig
	.scl(scl_sig) ,	// output  scl_sig
	.sda(sda_sig) 	// inout  sda_sig
);

