	soc_system u0 (
		.adc_input_data_export                    (<connected-to-adc_input_data_export>),                    //                    adc_input_data.export
		.adc_sel_channel_export                   (<connected-to-adc_sel_channel_export>),                   //                   adc_sel_channel.export
		.alarm_div_32_export                      (<connected-to-alarm_div_32_export>),                      //                      alarm_div_32.export
		.button_pio_external_connection_export    (<connected-to-button_pio_external_connection_export>),    //    button_pio_external_connection.export
		.buttons_inicio_emer_final_control_export (<connected-to-buttons_inicio_emer_final_control_export>), // buttons_inicio_emer_final_control.export
		.clk_clk                                  (<connected-to-clk_clk>),                                  //                               clk.clk
		.dipsw_pio_external_connection_export     (<connected-to-dipsw_pio_external_connection_export>),     //     dipsw_pio_external_connection.export
		.electro_control_export                   (<connected-to-electro_control_export>),                   //                   electro_control.export
		.hps_0_f2h_cold_reset_req_reset_n         (<connected-to-hps_0_f2h_cold_reset_req_reset_n>),         //          hps_0_f2h_cold_reset_req.reset_n
		.hps_0_f2h_debug_reset_req_reset_n        (<connected-to-hps_0_f2h_debug_reset_req_reset_n>),        //         hps_0_f2h_debug_reset_req.reset_n
		.hps_0_f2h_stm_hw_events_stm_hwevents     (<connected-to-hps_0_f2h_stm_hw_events_stm_hwevents>),     //           hps_0_f2h_stm_hw_events.stm_hwevents
		.hps_0_f2h_warm_reset_req_reset_n         (<connected-to-hps_0_f2h_warm_reset_req_reset_n>),         //          hps_0_f2h_warm_reset_req.reset_n
		.hps_0_h2f_reset_reset_n                  (<connected-to-hps_0_h2f_reset_reset_n>),                  //                   hps_0_h2f_reset.reset_n
		.hps_0_hps_io_hps_io_emac1_inst_TX_CLK    (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TX_CLK>),    //                      hps_0_hps_io.hps_io_emac1_inst_TX_CLK
		.hps_0_hps_io_hps_io_emac1_inst_TXD0      (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD0>),      //                                  .hps_io_emac1_inst_TXD0
		.hps_0_hps_io_hps_io_emac1_inst_TXD1      (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD1>),      //                                  .hps_io_emac1_inst_TXD1
		.hps_0_hps_io_hps_io_emac1_inst_TXD2      (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD2>),      //                                  .hps_io_emac1_inst_TXD2
		.hps_0_hps_io_hps_io_emac1_inst_TXD3      (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD3>),      //                                  .hps_io_emac1_inst_TXD3
		.hps_0_hps_io_hps_io_emac1_inst_RXD0      (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD0>),      //                                  .hps_io_emac1_inst_RXD0
		.hps_0_hps_io_hps_io_emac1_inst_MDIO      (<connected-to-hps_0_hps_io_hps_io_emac1_inst_MDIO>),      //                                  .hps_io_emac1_inst_MDIO
		.hps_0_hps_io_hps_io_emac1_inst_MDC       (<connected-to-hps_0_hps_io_hps_io_emac1_inst_MDC>),       //                                  .hps_io_emac1_inst_MDC
		.hps_0_hps_io_hps_io_emac1_inst_RX_CTL    (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RX_CTL>),    //                                  .hps_io_emac1_inst_RX_CTL
		.hps_0_hps_io_hps_io_emac1_inst_TX_CTL    (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TX_CTL>),    //                                  .hps_io_emac1_inst_TX_CTL
		.hps_0_hps_io_hps_io_emac1_inst_RX_CLK    (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RX_CLK>),    //                                  .hps_io_emac1_inst_RX_CLK
		.hps_0_hps_io_hps_io_emac1_inst_RXD1      (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD1>),      //                                  .hps_io_emac1_inst_RXD1
		.hps_0_hps_io_hps_io_emac1_inst_RXD2      (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD2>),      //                                  .hps_io_emac1_inst_RXD2
		.hps_0_hps_io_hps_io_emac1_inst_RXD3      (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD3>),      //                                  .hps_io_emac1_inst_RXD3
		.hps_0_hps_io_hps_io_sdio_inst_CMD        (<connected-to-hps_0_hps_io_hps_io_sdio_inst_CMD>),        //                                  .hps_io_sdio_inst_CMD
		.hps_0_hps_io_hps_io_sdio_inst_D0         (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D0>),         //                                  .hps_io_sdio_inst_D0
		.hps_0_hps_io_hps_io_sdio_inst_D1         (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D1>),         //                                  .hps_io_sdio_inst_D1
		.hps_0_hps_io_hps_io_sdio_inst_CLK        (<connected-to-hps_0_hps_io_hps_io_sdio_inst_CLK>),        //                                  .hps_io_sdio_inst_CLK
		.hps_0_hps_io_hps_io_sdio_inst_D2         (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D2>),         //                                  .hps_io_sdio_inst_D2
		.hps_0_hps_io_hps_io_sdio_inst_D3         (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D3>),         //                                  .hps_io_sdio_inst_D3
		.hps_0_hps_io_hps_io_usb1_inst_D0         (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D0>),         //                                  .hps_io_usb1_inst_D0
		.hps_0_hps_io_hps_io_usb1_inst_D1         (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D1>),         //                                  .hps_io_usb1_inst_D1
		.hps_0_hps_io_hps_io_usb1_inst_D2         (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D2>),         //                                  .hps_io_usb1_inst_D2
		.hps_0_hps_io_hps_io_usb1_inst_D3         (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D3>),         //                                  .hps_io_usb1_inst_D3
		.hps_0_hps_io_hps_io_usb1_inst_D4         (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D4>),         //                                  .hps_io_usb1_inst_D4
		.hps_0_hps_io_hps_io_usb1_inst_D5         (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D5>),         //                                  .hps_io_usb1_inst_D5
		.hps_0_hps_io_hps_io_usb1_inst_D6         (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D6>),         //                                  .hps_io_usb1_inst_D6
		.hps_0_hps_io_hps_io_usb1_inst_D7         (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D7>),         //                                  .hps_io_usb1_inst_D7
		.hps_0_hps_io_hps_io_usb1_inst_CLK        (<connected-to-hps_0_hps_io_hps_io_usb1_inst_CLK>),        //                                  .hps_io_usb1_inst_CLK
		.hps_0_hps_io_hps_io_usb1_inst_STP        (<connected-to-hps_0_hps_io_hps_io_usb1_inst_STP>),        //                                  .hps_io_usb1_inst_STP
		.hps_0_hps_io_hps_io_usb1_inst_DIR        (<connected-to-hps_0_hps_io_hps_io_usb1_inst_DIR>),        //                                  .hps_io_usb1_inst_DIR
		.hps_0_hps_io_hps_io_usb1_inst_NXT        (<connected-to-hps_0_hps_io_hps_io_usb1_inst_NXT>),        //                                  .hps_io_usb1_inst_NXT
		.hps_0_hps_io_hps_io_uart0_inst_RX        (<connected-to-hps_0_hps_io_hps_io_uart0_inst_RX>),        //                                  .hps_io_uart0_inst_RX
		.hps_0_hps_io_hps_io_uart0_inst_TX        (<connected-to-hps_0_hps_io_hps_io_uart0_inst_TX>),        //                                  .hps_io_uart0_inst_TX
		.hps_0_hps_io_hps_io_gpio_inst_GPIO09     (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO09>),     //                                  .hps_io_gpio_inst_GPIO09
		.hps_0_hps_io_hps_io_gpio_inst_GPIO35     (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO35>),     //                                  .hps_io_gpio_inst_GPIO35
		.hps_0_hps_io_hps_io_gpio_inst_GPIO40     (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO40>),     //                                  .hps_io_gpio_inst_GPIO40
		.hps_0_hps_io_hps_io_gpio_inst_GPIO53     (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO53>),     //                                  .hps_io_gpio_inst_GPIO53
		.hps_0_hps_io_hps_io_gpio_inst_GPIO54     (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO54>),     //                                  .hps_io_gpio_inst_GPIO54
		.hps_0_hps_io_hps_io_gpio_inst_GPIO61     (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO61>),     //                                  .hps_io_gpio_inst_GPIO61
		.hps_0_i2c0_out_data                      (<connected-to-hps_0_i2c0_out_data>),                      //                        hps_0_i2c0.out_data
		.hps_0_i2c0_sda                           (<connected-to-hps_0_i2c0_sda>),                           //                                  .sda
		.hps_0_i2c0_clk_clk                       (<connected-to-hps_0_i2c0_clk_clk>),                       //                    hps_0_i2c0_clk.clk
		.hps_0_i2c0_scl_in_clk                    (<connected-to-hps_0_i2c0_scl_in_clk>),                    //                 hps_0_i2c0_scl_in.clk
		.led_pio_external_connection_export       (<connected-to-led_pio_external_connection_export>),       //       led_pio_external_connection.export
		.max6675_temp_export                      (<connected-to-max6675_temp_export>),                      //                      max6675_temp.export
		.memory_mem_a                             (<connected-to-memory_mem_a>),                             //                            memory.mem_a
		.memory_mem_ba                            (<connected-to-memory_mem_ba>),                            //                                  .mem_ba
		.memory_mem_ck                            (<connected-to-memory_mem_ck>),                            //                                  .mem_ck
		.memory_mem_ck_n                          (<connected-to-memory_mem_ck_n>),                          //                                  .mem_ck_n
		.memory_mem_cke                           (<connected-to-memory_mem_cke>),                           //                                  .mem_cke
		.memory_mem_cs_n                          (<connected-to-memory_mem_cs_n>),                          //                                  .mem_cs_n
		.memory_mem_ras_n                         (<connected-to-memory_mem_ras_n>),                         //                                  .mem_ras_n
		.memory_mem_cas_n                         (<connected-to-memory_mem_cas_n>),                         //                                  .mem_cas_n
		.memory_mem_we_n                          (<connected-to-memory_mem_we_n>),                          //                                  .mem_we_n
		.memory_mem_reset_n                       (<connected-to-memory_mem_reset_n>),                       //                                  .mem_reset_n
		.memory_mem_dq                            (<connected-to-memory_mem_dq>),                            //                                  .mem_dq
		.memory_mem_dqs                           (<connected-to-memory_mem_dqs>),                           //                                  .mem_dqs
		.memory_mem_dqs_n                         (<connected-to-memory_mem_dqs_n>),                         //                                  .mem_dqs_n
		.memory_mem_odt                           (<connected-to-memory_mem_odt>),                           //                                  .mem_odt
		.memory_mem_dm                            (<connected-to-memory_mem_dm>),                            //                                  .mem_dm
		.memory_oct_rzqin                         (<connected-to-memory_oct_rzqin>),                         //                                  .oct_rzqin
		.mosfet_control_export                    (<connected-to-mosfet_control_export>),                    //                    mosfet_control.export
		.mosfet_en_export                         (<connected-to-mosfet_en_export>),                         //                         mosfet_en.export
		.printer_uart_cts                         (<connected-to-printer_uart_cts>),                         //                      printer_uart.cts
		.printer_uart_dsr                         (<connected-to-printer_uart_dsr>),                         //                                  .dsr
		.printer_uart_dcd                         (<connected-to-printer_uart_dcd>),                         //                                  .dcd
		.printer_uart_ri                          (<connected-to-printer_uart_ri>),                          //                                  .ri
		.printer_uart_dtr                         (<connected-to-printer_uart_dtr>),                         //                                  .dtr
		.printer_uart_rts                         (<connected-to-printer_uart_rts>),                         //                                  .rts
		.printer_uart_out1_n                      (<connected-to-printer_uart_out1_n>),                      //                                  .out1_n
		.printer_uart_out2_n                      (<connected-to-printer_uart_out2_n>),                      //                                  .out2_n
		.printer_uart_rxd                         (<connected-to-printer_uart_rxd>),                         //                                  .rxd
		.printer_uart_txd                         (<connected-to-printer_uart_txd>),                         //                                  .txd
		.reset_reset_n                            (<connected-to-reset_reset_n>),                            //                             reset.reset_n
		.sel_max6675_export                       (<connected-to-sel_max6675_export>),                       //                       sel_max6675.export
		.uart_rx_lcd_in_writedata                 (<connected-to-uart_rx_lcd_in_writedata>),                 //                    uart_rx_lcd_in.writedata
		.uart_rx_lcd_in_write                     (<connected-to-uart_rx_lcd_in_write>),                     //                                  .write
		.uart_rx_lcd_in_waitrequest               (<connected-to-uart_rx_lcd_in_waitrequest>),               //                                  .waitrequest
		.uart_tx_lcd_out_readdata                 (<connected-to-uart_tx_lcd_out_readdata>),                 //                   uart_tx_lcd_out.readdata
		.uart_tx_lcd_out_read                     (<connected-to-uart_tx_lcd_out_read>),                     //                                  .read
		.uart_tx_lcd_out_waitrequest              (<connected-to-uart_tx_lcd_out_waitrequest>),              //                                  .waitrequest
		.valves_control_export                    (<connected-to-valves_control_export>)                     //                    valves_control.export
	);

